// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoCommand.h"
#include "AutoDrive.h"
#include "AutoTurn.h"
#include "AutoShoot.h"
#include "Delay.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoCommand::AutoCommand(std::string mode): CommandGroup() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.


	// There was a more elegant solution for auto selection, but typing issues forced a change to this system.
	// Robot is 36inch from front to back with bumpers
	// run auto #0 "StraightGear"
	if(mode == "auto0")
	{
		AddSequential(new AutoDrive(112 - 36, false, 6)); // 111 too high. Find out robot width
	//	Robot::gear->tilt->Set(DoubleSolenoid::kForward); // Tilt gear forward
	}

	// run auto #1
	else if(mode == "auto1")
	{
		AddSequential(new AutoDrive(114.5 - 18, false, 3.5)); // Drive gear-first (backwards) until chalk line is reached
		AddSequential(new AutoTurn(60, false, 3.5)); // Turn 60deg counterclockwise to align with gear peg
		AddSequential(new Delay(0.75));
		AddSequential(new AutoDrive(45, false, 3)); // Drive remaining 45inch to get gear onto peg.
		Robot::shooter->mDesiredSpeed = 1400; // Shoot speed automatically reverts to the preference at TeleopInit
		AddSequential(new AutoShoot(6)); // Shoot for 6 seconds
		//AddSequential(new AutoTurn(90, true, 7));
		//AddSequential(new AutoTurn(90, false, 5));
	}

	// run auto #2 "BlueShootCross"
	else if(mode == "auto2")
	{
		Robot::shooter->mDesiredSpeed = 1020;
		Robot::shooter->mShoot = true;
		AddSequential(new Delay(1));
		AddSequential(new AutoShoot(4)); // shoot 4 seconds
		AddSequential(new AutoTurn(90, true, 4));
		AddSequential(new Delay(0.75));
		AddSequential(new AutoDrive(120, true, 4));

	}

	// run auto #3 "BlueShootGear"
	else if(mode == "auto3")
	{
		Robot::shooter->mDesiredSpeed = 1020;
		Robot::shooter->mShoot = true;
		AddSequential(new Delay(1));
		AddSequential(new AutoShoot(4));
		AddSequential(new AutoTurn(88, false, 4));
		AddSequential(new AutoDrive(80, false, 4)); // 114inch from alliance wall to near face of airship. Subtract robot width from 114"
		AddSequential(new AutoTurn(60, true, 4));
		AddSequential(new Delay(0.75));
		AddSequential(new AutoDrive(45, false, 4));
	}

	// run auto #4 "RedShootCross"
	else if(mode == "auto4")
	{
		Robot::shooter->mDesiredSpeed = 1020;
		Robot::shooter->mShoot = true;
		AddSequential(new Delay(1));
		AddSequential(new AutoShoot(2));
		AddSequential(new AutoTurn(90, false, 4));
		AddSequential(new Delay(0.75));
		AddSequential(new AutoDrive(120, true, 4));
	}

	// run auto #5 "RedShootGear"
	else if(mode == "auto5")
	{
		Robot::shooter->mDesiredSpeed = 1020;
		Robot::shooter->mShoot = true;
		AddSequential(new Delay(1));
		AddSequential(new AutoShoot(2));
		AddSequential(new AutoTurn(88, true, 4));
		AddSequential(new AutoDrive(83, false, 4)); // 114inch from alliance wall to near face of airship. Subtract robot width from 114"
		AddSequential(new AutoTurn(60, false, 4));
		AddSequential(new Delay(0.75));
		AddSequential(new AutoDrive(45, false, 4));
	}

	// run auto #6 "BlueFarGear"
	else if(mode == "auto6")
	{
		AddSequential(new AutoDrive(90, false, 4)); // 114inch from alliance wall to near face of airship. Subtract robot width from 114"
		// CHECK THE ABOVE DISTANCE!!!
		AddSequential(new AutoTurn(57, false, 4));
		AddSequential(new Delay(0.75));
		AddSequential(new AutoDrive(40, false, 4));
	}

	// run auto #7 "RedFarGear"
	else if(mode == "auto7")
	{
		AddSequential(new AutoDrive(90, false, 4)); // 114inch from alliance wall to near face of airship. Subtract robot width from 114"
		// CHECK THE ABOVE DISTANCE!!!
		AddSequential(new AutoTurn(57, true, 4));
		AddSequential(new Delay(0.75));
		AddSequential(new AutoDrive(40, false, 4));
	}
 }
