// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoTurn.h"


AutoTurn::AutoTurn(float desiredDegrees, bool clockwise, double timeout): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	m_desiredDegrees = desiredDegrees;
	m_clockwise = clockwise;
	m_timeout = timeout;
}


// Called just before this Command runs the first time
void AutoTurn::Initialize() {
	SetTimeout(m_timeout);
	// TODO: determine if calibrating here is appropriate (ample time to calibrate?)
	Robot::chassis->gyro->Calibrate();
	Robot::chassis->leftEncoder->Reset();
	Robot::chassis->rightEncoder->Reset();
}

// Called repeatedly when this Command is scheduled to run
void AutoTurn::Execute() {

}

// Make this return true when this Command no longer needs to run execute()
bool AutoTurn::IsFinished() {
	// TODO: add condition for reaching desired angle
    return IsTimedOut();
}

// Called once after isFinished returns true
void AutoTurn::End() {
	Robot::chassis->leftA->Set(0.0);
	Robot::chassis->leftB->Set(0.0);
	Robot::chassis->rightA->Set(0.0);
	Robot::chassis->rightB->Set(0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoTurn::Interrupted() {
	Robot::chassis->leftA->Set(0.0);
	Robot::chassis->leftB->Set(0.0);
	Robot::chassis->rightA->Set(0.0);
	Robot::chassis->rightB->Set(0.0);
}
