// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoCommand.h"
#include "AutoDrive.h"
#include "AutoTurn.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoCommand::AutoCommand(std::string mode): CommandGroup() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.

    // To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.


	// There was a more elegant solution for auto selection, but typing issues forced a change to this system.
	// run auto #0
	if(mode == "auto0")
	{
		AddSequential(new AutoDrive(120, true, 6));
	}

	// run auto #1
	else if(mode == "auto1")
	{
		AddSequential(new AutoTurn(90, true, 5));
		AddSequential(new AutoTurn(90, false, 5));
	}
 }
