// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ChassisReverse.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ChassisReverse::ChassisReverse(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::chassis.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ChassisReverse::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ChassisReverse::Execute() {
	if (Robot::chassis->m_isReversed)
	{
		Robot::chassis->leftA->SetInverted(false);
		Robot::chassis->leftB->SetInverted(false);
		Robot::chassis->rightA->SetInverted(false);
		Robot::chassis->rightB->SetInverted(false);
		Robot::chassis->m_isReversed = false;
	}
	else
	{
		Robot::chassis->leftA->SetInverted(true);
		Robot::chassis->leftB->SetInverted(true);
		Robot::chassis->rightA->SetInverted(true);
		Robot::chassis->rightB->SetInverted(true);
		Robot::chassis->m_isReversed = true;
	}
}

// Make this return true when this Command no longer needs to run execute()
bool ChassisReverse::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void ChassisReverse::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ChassisReverse::Interrupted() {

}
